#!/bin/bash
set -eo pipefail

# This script runs the wallabag application locally using Docker Compose

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}=== Wallabag Local Runner ===${NC}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# Check if .env file exists
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Warning: .env file not found. Creating from .env.example${NC}"
    cp .env.example .env
    echo -e "${YELLOW}Please edit .env file with your database credentials before proceeding.${NC}"
    exit 1
fi

# Check if docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed. Please install Docker and try again.${NC}"
    exit 1
fi

# Check if docker-compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}Error: docker-compose is not installed. Please install Docker Compose and try again.${NC}"
    exit 1
fi

# Check if Docker is running
if ! docker info &> /dev/null; then
    echo -e "${RED}Error: Docker is not running. Please start Docker and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}Starting Wallabag using Docker Compose...${NC}"

# Check if image exists, if not build it
if ! docker images | grep -q 'self-wallabag'; then
    echo -e "${YELLOW}Wallabag image not found. Building it first...${NC}"
    chmod +x backend/src/scripts/build-wallabag.sh
    ./backend/src/scripts/build-wallabag.sh
fi

# Start the containers
docker-compose up -d

# Wait for the service to be ready
echo -e "${GREEN}Waiting for Wallabag to start...${NC}"
attempt=0
max_attempts=30

while [ $attempt -lt $max_attempts ]; do
    status=$(docker inspect --format='{{.State.Health.Status}}' self-wallabag 2>/dev/null || echo "not_created")
    
    if [ "$status" = "healthy" ]; then
        echo -e "${GREEN}Wallabag is now running!${NC}"
        break
    elif [ "$status" = "not_created" ]; then
        echo -e "${RED}Container not found. Make sure it's running.${NC}"
        break
    fi
    
    attempt=$((attempt+1))
    echo -n "."
    sleep 2
done

echo
echo -e "${GREEN}=====================================${NC}"
echo -e "${GREEN}Wallabag is available at: http://localhost:8080${NC}"
echo
echo -e "${BLUE}Admin Credentials:${NC}"
echo -e "Username: admin"
echo -e "Password: <auto-generated>"
echo
echo -e "${YELLOW}To view the auto-generated password:${NC}"
echo -e "docker exec self-wallabag cat /var/www/html/data/initial-admin-password.txt"
echo
echo -e "${YELLOW}To view API key (if enabled):${NC}"
echo -e "docker exec self-wallabag cat /var/www/html/data/keys/api-key.txt"
echo
echo -e "${GREEN}To stop Wallabag:${NC}"
echo -e "docker-compose down"
echo -e "${GREEN}=====================================${NC}"

exit 0