openapi: 3.0.0
info:
  title: Wallabag Articles API
  description: API endpoints for managing articles in Wallabag
  version: 1.0.0

servers:
  - url: https://wallabag.example.com/api
    description: Self-hosted Wallabag API

paths:
  /entries:
    get:
      summary: Get all articles
      description: Retrieves a list of articles with optional filtering
      operationId: getEntries
      tags:
        - Articles
      security:
        - BearerAuth: []
      parameters:
        - name: archive
          in: query
          description: Filter by archived status
          schema:
            type: integer
            enum: [0, 1, 2]
            default: 2
        - name: starred
          in: query
          description: Filter by starred status
          schema:
            type: integer
            enum: [0, 1, 2]
            default: 2
        - name: sort
          in: query
          description: Sort field
          schema:
            type: string
            enum: [created, updated, archived]
            default: created
        - name: order
          in: query
          description: Sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          description: Items per page
          schema:
            type: integer
            default: 30
        - name: tags
          in: query
          description: Filter by tags (comma-separated)
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  limit:
                    type: integer
                  pages:
                    type: integer
                  total:
                    type: integer
                  _links:
                    type: object
                  _embedded:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Article'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      summary: Create article
      description: Creates a new article from URL
      operationId: createEntry
      tags:
        - Articles
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  description: URL of the article to save
                title:
                  type: string
                  description: Custom title (optional)
                tags:
                  type: array
                  items:
                    type: string
                  description: Tags to apply to the article
                archived:
                  type: boolean
                  description: Whether to mark as archived
                starred:
                  type: boolean
                  description: Whether to mark as starred
      responses:
        '200':
          description: Article successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /entries/{id}:
    get:
      summary: Get article by ID
      description: Retrieves an article by its ID
      operationId: getEntry
      tags:
        - Articles
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Article not found
    patch:
      summary: Update article
      description: Updates an existing article
      operationId: updateEntry
      tags:
        - Articles
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: New title
                archived:
                  type: boolean
                  description: Whether to mark as archived
                starred:
                  type: boolean
                  description: Whether to mark as starred
                tags:
                  type: array
                  items:
                    type: string
                  description: Updated tags (replaces existing tags)
      responses:
        '200':
          description: Article successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Article not found
    delete:
      summary: Delete article
      description: Deletes an article
      operationId: deleteEntry
      tags:
        - Articles
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
      responses:
        '200':
          description: Article successfully deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Article not found

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          description: Article ID
        title:
          type: string
          description: Article title
        url:
          type: string
          format: uri
          description: Original article URL
        content:
          type: string
          description: Article content (HTML)
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
        reading_time:
          type: integer
          description: Estimated reading time in minutes
        domain_name:
          type: string
          description: Domain of the article
        language:
          type: string
          description: Detected language code
        is_archived:
          type: boolean
          description: Whether the article is archived
        is_starred:
          type: boolean
          description: Whether the article is starred
        preview_picture:
          type: string
          format: uri
          nullable: true
          description: URL to a preview image
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    
    Tag:
      type: object
      properties:
        id:
          type: integer
          description: Tag ID
        label:
          type: string
          description: Tag label
        slug:
          type: string
          description: URL-friendly tag name
  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT